### ISSUE TITLE
Screenshots for React-Java-MySQL are off

### ISSUE THREAD

**Issue by JalexChen** [docker/awesome-compose#285]
I understand this is a very small issue but the screenshots in the README for the mentioned [directory](https://github.com/docker/awesome-compose/tree/master/react-java-mysql) is a bit off and/or outdated, and I only ran into this when my CI build was failing as a result. 

I was testing for `react-java-mysql_backend` when in reality, the container was named `react-java-mysql-backend`

![Screen Shot 2022-09-13 at 2 49 22 PM](https://user-images.githubusercontent.com/14379129/190015857-fc8da0e8-e448-4fa3-af1c-998f296f0c7f.png)

Might be a coincidence but my lead  posted a relevant article just today which I thought was humorous: https://joshtronic.com/2022/08/21/screenshots-are-not-documentation/

Thank you Docker team for providing this repository! :)

**Comment by nicksieger** [comment]
You're right, good eye! A lot of the READMEs appear to show output from compose v1. In compose v2 we're using dashes instead of underscores for image and container names. The format is a bit different as well. Would you mind submitting a PR for those changes? A lot of the samples need updating, but feel free to just update the react-java-mysql one.

**Comment by JalexChen** [comment]
Sure thing. I thought they were screenshots initially but I've just submitted a PR
