### ISSUE TITLE
Missing hyphen in nginx-wsgi-flask readme

### ISSUE THREAD

**Issue by DJStompZone** [docker/awesome-compose#425]
### Description

In awesome-compose/nginx-wsgi-flask/README.md, `docker compose` is erroneously used in two of the code blocks, rather than `docker-compose`.

### Proposed solution

Add missing hyphen to those instances of `docker compose`

Fixed by #424

**Comment by glours** [comment]
Hey @DJStompZone 
Compose is a Docker CLI since it was rewrote in Golang, you can use `docker compose` for [more than 2 years now](https://www.docker.com/blog/announcing-compose-v2-general-availability/).
If you're not still using a version `v1.x` of Compose, I encourage you to [migrate](https://docs.docker.com/compose/migrate/)  as Compose v1 reach end of life and is not maintained anymore.
