### ISSUE TITLE
This project is abandoned? 

### ISSUE THREAD

**Issue by xe-nvdk** [docker/awesome-compose#65]
Hi guys, the last PR was committed 21 days ago, and after that 2 months ago. This project is left behind?

Thanks.

**Comment by carehart** [comment]
You're asking that after just 3 weeks? I guess you spend your days in some VERY active github community projects. :-) 

I'm not involved in organizing things here, though I have contributed, so I'm just sharing my opinion in case it may help (since your question is unanswered after 9 hours). 

As people contribute things, or ask about them, they are considered and may be added by the organizers. (I don't think they committed to adding new examples themselves with any regularity.) 

I suppose someone may wonder, "well, why aren't more people adding examples more often?" That's a bit like pushing rope, isn't it?  :-) Perhaps it identifies an opportunity for more people to share news of the project more widely, to get more contribution. That would be a positive response to your observation. For perspective, the project is barely 4 months old. 

Even so, as the purpose is simply to be a repository of docker-compose examples, it would seem that even if no one ever contributed another one, those there now might well work fine for folks for years to come, and the project will have served a purpose. :-) 

And if any examples ever don't work well, then people using them will report their issues and interested folks will attend to them. I suppose we might well consider the project abandoned if such issues or PRs were NOT being addressed after weeks or months. 

That said, it sure seems I've observed that they (the organizers) have responded quite quickly to any issues or PRs. Still, I don't think there's any company behind this, providing paid staff. I don't even hold it against them that no one responded to this after 9 hours. I suspect they may have multiple irons in the fire--and it's a crazy time right now for many, on multiple levels..

Anyway, I'm just offering a different perspective. I don't mean it to sound critical. I do hope it may be helpful.

**Comment by xe-nvdk** [comment]
Is doesn't matter how I spend my time in GitHub, You don't know me, so, I will not take your "VERY" as a personal attack.

I made a simple, honest, and without second intention question-based in what I saw here.

Stay safe and have a good evening.

**Comment by carehart** [comment]
If anyone can tell me what I said that could be offensive, I'd welcome the feedback.
